# Generated by Django 5.0.6 on 2025-11-08 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbeiro',
            old_name='descricao',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='barbeiro',
            name='nome',
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='barbeiro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='barbeiros/'),
        ),
        migrations.AlterField(
            model_name='barbeiro',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marcacao',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao_min',
            field=models.PositiveIntegerField(help_text='Duração em minutos'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
